### ISSUE TITLE
How to understand inverse predictive loss 

### ISSUE THREAD

**Issue by Some-random** [yaohungt/Demystifying_Self_Supervised_Learning#1]
I've read your paper but I'm having a hard time understanding inverse predictive loss. Judging from Figure 2, it seems to be a loss between the mapping of Zx to Zs, but in your [code](https://github.com/yaohungt/Demystifying_Self_Supervised_Learning/blob/master/Omniglot/main.py#L54), it became MSE loss. Can you explain it a bit more please?

**Comment by yaohungt** [comment]
Hi, the idea of inverse predictive loss is from S to Z_X. Leveraging the existing network, we reuse the network S->Z_S. Hence, the inverse predictive loss becomes Z_S to Z_X. We use a Gaussian as the variational distribution from Z_S to Z_X. This choice admits a MSE loss between Z_S and Z_X.

**Comment by Leeyouxie** [comment]
> Hi, the idea of inverse predictive loss is from S to Z_X. Leveraging the existing network, we reuse the network S->Z_S. Hence, the inverse predictive loss becomes Z_S to Z_X. We use a Gaussian as the variational distribution from Z_S to Z_X. This choice admits a MSE loss between Z_S and Z_X.

Hi, in your paper, you try to maximize the log conditional likelihood from the self-supervised signal S to the learned representation Zx for the inverse predictive learning. However, in the function "inverse_perdictive_loss", two MSE losses between Zx and Zs are used for inverse predictive learning. Can you give me some explanations about this? Moreover, in function "inverse_perdictive_loss", it seems that you compute the same MSE loss twice.

**Comment by yaohungt** [comment]
The adoption of MSE losses is because of assuming a Gaussian distribution between Z_X and Z_S. This approximation may not be the best one, but is the simplest one. Another common choice is Laplacian, when the loss becomes MAE loss. 

The reason why the losses are performed between Z_X and Z_S (not between Z_X and S) is that we reuse the network S -> Z_S. You can also not have this choice. For example, you can perform the MSE losses between q(S) and Z_X, where q(\cdot) is another neural network that is different from the network in S -> Z_S.

The reason for two MSE losses is because in visual representation learning experiments, we can swap the input and the self-supervised signal.

**Comment by Leeyouxie** [comment]
> ming a Gaussian distribution between Z_X and Z_S. This approximation may not be the best one, but is the simplest one. Another common choice is Laplacian, w

Thanks for your reply. If MSE is used in inverse predictive learning, it seems that inverse predictive learning makes it easy for the network to learn contrastive learning.  I am not sure whether I got the right understanding.

**Comment by yaohungt** [comment]
Why "makes it easy for the network to learn contrastive learning"? Can you elaborate on it more?

**Comment by Some-random** [comment]
> Why "makes it easy for the network to learn contrastive learning"? Can you elaborate on it more?

If MSE is properly optimized, then Zx and Zs would essentially be the same. And the output through G network would also be the same. So there is no need to use NT-Xent loss at the output.

**Comment by yaohungt** [comment]
This is incorrect. We don't want the outputs are the same given arbitrary inputs. We still need the contrastive loss to avoid the trivial solutions.

**Comment by yaohungt** [comment]
I'll close this issue as I don't think there's a confusion here.

**Comment by Some-random** [comment]
Sorry if what I said before was unclear. In the case of SimCLR, what I meant is it seems like the optimization of inverse learning constitutes the optimization of NT-Xent. These two objectives don't seem to be complementary...

**Comment by yaohungt** [comment]
On the one hand, the contrastive loss maximizes the contrastiveness between the samples from the joint distribution and the samples from the product of marginal distributions. On the other hand, inverse predictive loss minimizes the redundant information in the input that is not relevant to the self-supervised signal. The two objectives are different and aim for various goals.

**Comment by Some-random** [comment]
Thank you for your explanation! I can understand it now.

**Comment by yaohungt** [comment]
You are welcome! And I will soon have a completely new version of the paper, where more analysis will be included and I will relax the strong assumption I had in the paper.

**Comment by Some-random** [comment]
That's great to hear! Can you let us know (like leaving another comment in this thread) when your new paper will be released? We're currently working on the application of contrastive representation learning to speech and we're trying to incorporate the findings in your paper into our work.

**Comment by yaohungt** [comment]
Will do. Thanks!

**Comment by yaohungt** [comment]
Here's the updated version. It relaxes the strong conditional independence assumption.
